version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true